deployment:
  name: prod-school2
  replicaCount: 1
  deadlinesec: 60
  restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  image:
    repository: gitlab_ci
    tag: gitlab_ci
    pullPolicy: Always
  ports:
  - name: web
    containerPort: 3000
    protocol: TCP
  liveness:
    httpGet:
      path: /api/health/live
      port: 3000
    initialDelaySeconds: 15
    timeoutSeconds: 10
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  tolerations: {}
  nodeSelector: {}
  affinity: {}
  secrets: []
  


service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: web

ingress:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host:  miniapp-wizard2.yarus.ru
      paths: /
      svc_name: prod-school2
      svc_port: 3000
      secretName: yarus-tls
